KTB-08 Проверять правильность ответа пользователя
VladWhite22/KotlinTelegramBot pull request #6
Opened 2024-12-25 12:57 UTC by VladWhite22

2024-12-26 13:07 UTC, dzenonce requested changes

2024-12-26 13:07 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +    File("words.txt").delete()
А зачем здесь удалять файл словаря, можно же просто перезаписать его пустой строкой, тем более имя файла дублируется, лучше в константу

2024-12-26 13:07 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +                    correctAnswer.correctAnswersCount += 1
Можно короче `correctAnswer.correctAnswersCount++`

2024-12-26 14:05 UTC, VladWhite22 commented
Сейчас файл перезаписывается в виде: [hello|привет|0
, dog|собака|0
, cat|кошка|0
, home|дом|1
, orange|апельсин|1
], Дмитрий скажи пожалуйста как сделать запись в виде :
dog|собака|0
cat|кошка|0
home|дом|1
orange|апельсин|1

2024-12-26 16:47 UTC, dzenonce requested changes

2024-12-26 16:47 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +    File(WORDS).writeText("")
Все же лучше открыть файл и сохранить на него ссылку в переменную и обращаться к ней

2024-12-26 16:47 UTC, dzenonce commented on src/main/kotlin/Main.kt
> +    File(WORDS).writeText(dictionary.map { "${it.original}|${it.translete}|${it.correctAnswersCount}\n" }.toString())
Здесь неправильный формат потому что ты делаешь map он и записывает все разделители

Корректно так:

```
for (word in words) {
            wordsFile.appendText("${word.original}|${word.translate}|${word.correctAnswersCount}\n")
        }
```

2024-12-27 15:53 UTC, dzenonce approved these changes
Теперь все верно, но слова должны изучаться в цикле, т.е не выходить в меню, пока не выбран соответствующий пункт меню или не выучены все слова в списке

2025-01-12 01:00 UTC, merged